### ISSUE TITLE
Story creation: Bottom sheet

### ISSUE THREAD

**Issue by aforcier** [Automattic/portkey-android#194]
### **UPDATE**
Latest design

<img width="756" alt="publishing-i3-story-cover" src="https://user-images.githubusercontent.com/6597771/81961617-fbf04400-95e8-11ea-89f8-9181378574a6.png">

### OLD DESCRIPTION

- [ ] Bottom sheet "Post and add to…[New story]" appears.
- [ ] Implement bottom sheet
- [ ] Implement snackbar "[Story title] created" / "Added to [story title]"

![publishing-flow-with-options-1](https://user-images.githubusercontent.com/6597771/76640994-a4bdec80-652f-11ea-87b7-0553a35b68de.png)

![publishing-flow-options-with-icon](https://user-images.githubusercontent.com/6597771/76640985-a12a6580-652f-11ea-9b91-22ca23c78d94.png)

Also note:
- [ ] tapping on the arrow expands the options and then leaves it expanded (with the bottom sheet growing its size)
- [ ] site name and icon should be shown conditionally, only for multisite users (users with just one site will not see this).
- [ ] follow [Google Web Stories guidelines](https://mobilelabp2.files.wordpress.com/2020/02/external-web-stories-guidelines.pdf) about title: under 40 char limit and mandatory

**Comment by mzorz** [comment]
This is merged! 

For historic purposes, collecting here all the PRs (merged and closed) that went into it 😅 

https://github.com/wordpress-mobile/WordPress-Android/pull/12442
https://github.com/wordpress-mobile/WordPress-Android/pull/12333
https://github.com/wordpress-mobile/WordPress-Android/pull/12330
https://github.com/wordpress-mobile/WordPress-Android/pull/12328
https://github.com/wordpress-mobile/WordPress-Android/pull/12307
https://github.com/wordpress-mobile/WordPress-Android/pull/12306
https://github.com/wordpress-mobile/WordPress-Android/pull/12532
https://github.com/wordpress-mobile/WordPress-Android/pull/12521
https://github.com/wordpress-mobile/WordPress-Android/pull/12520
https://github.com/wordpress-mobile/WordPress-Android/pull/12486

Great job @jd-alexander !
