### ISSUE TITLE
Analytics support

### ISSUE THREAD

**Issue by aforcier** [Automattic/portkey-android#476]
Add a tracking interface to allow the host app to track stories-internal interactions.

For now, we'd like to fire an event whenever an emoji or text is added. In the text case, let's have some properties attached to the event, like which font the user selected.

There are other things we could track but for now adding/removing frames or dragging/resizing events don't feel like they would give us useful information, so let's just keep it simple.

Update: Let's also track how often we end up having to use fallbacks for fonts (#494).

**Comment by aforcier** [comment]
Let's also have some way of tracking whether we had to crop or not, and how much horizontal or vertical cropping we had to do.

**Comment by aforcier** [comment]
One more tracking note (this one's WPAndroid-side): let's track how often users are editing existing stories.

**Comment by mzorz** [comment]
I had a few notes to share on this for when we get there.

Check [EditorTracker.kt](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/posts/editor/EditorTracker.kt), here we're tracking a few events related to the Editor including adding media, but also for interactions such as enabling/disabling bold, italic, and so on. See method `trackEditorEvent` there; we'll probably want to implement tracking in this way to keep things in a similar way.
 
Idea would be to add a new interface such as the one implemented in https://github.com/Automattic/stories-android/pull/362 (or even a more generic, enum-based event interface); we'd just need to make sure to add these events for `addedViews` and such in the implementation of that interface in the host app by either reusing EditorTracker on WPAndroid or creating a new class that goes along the same lines, called `StoryCreatorTracker` probably.

**Comment by mzorz** [comment]
Also note: https://github.com/Automattic/stories-android/issues/500
