### ISSUE TITLE
Missing resources in verifyReleaseResources task

### ISSUE THREAD

**Issue by oguzkocer** [Automattic/portkey-android#515]
I get the following errors when I run `./gradlew build` on current `develop`. I have seen this same error when I run the same command for https://github.com/wordpress-mobile/WordPress-Android since it'll also build the subprojects.

@aforcier @mzorz Could either of you take a look at this when you get a chance? I am looking into upgrading Gradle to 6 and I'd like to have a green build before the upgrade so I can verify the upgrade doesn't affect the build.

```
* What went wrong:
Execution failed for task ':stories:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/leweo/Developer/Projects/stories-android/stories/src/main/res/layout/fragment_story_frame_item_plus.xml:11: AAPT: error: resource drawable/ic_add_white_24dp (aka com.wordpress.stories:drawable/ic_add_white_24dp) not found.

     /Users/leweo/Developer/Projects/stories-android/stories/src/main/res/layout/view_compose_popup_menu.xml:2: AAPT: error: resource color/black_translucent_50 (aka com.wordpress.stories:color/black_translucent_50) not found.
```

**Comment by mzorz** [comment]
Thanks for the heads up @oguzkocer , made the fix in https://github.com/Automattic/stories-android/pull/516 and also created a PR to update the stories lib commit hash on WPAndroid here https://github.com/wordpress-mobile/WordPress-Android/pull/12944.
