### ISSUE TITLE
Bug: z index / elevation of objects in the story editor is different in the output

### ISSUE THREAD

**Issue by megsfulton** [Automattic/portkey-android#534]
> I took the first screenshot right before publishing, and the second is a screenshot of the story viewer. The emoji should be behind the text, but their ordering got mixed up on publish.

<img width="407" alt="Screen Shot 2020-09-16 at 5 21 33 PM" src="https://user-images.githubusercontent.com/161697/93405156-18bfb100-f841-11ea-833a-c19dd63d3db4.png">

**Comment by mzorz** [comment]
Wah nice find @megsfulton ! 💯

**Comment by megsfulton** [comment]
It was @mattmiklic who found this one!
