### ISSUE TITLE
Button updates

### ISSUE THREAD

**Issue by megsfulton** [Automattic/portkey-android#551]
Update the styling of the X, Publish, and Done buttons. 

These updates address the feedback we heard in Alpha 2 testing about the "done" button not being obvious. They also bring Android closer to the Kanvas UI. 

What's changing:
1) Adding a black transparent circle behind the X icon (same as the other icon buttons on the editing screen)
2) Changing the "Next" button to a white circle with the Material arrow icon. 
3) Replace the "done" text button with a white circle button with the Material check icon. 

<img width="1143" alt="Screen Shot 2020-09-28 at 2 02 57 PM" src="https://user-images.githubusercontent.com/161697/94485815-57cff980-0193-11eb-9308-abfcc4616432.png">

**Comment by aforcier** [comment]
@megsfulton what should the button be in the case where we're editing a story from Gutenberg (https://github.com/Automattic/stories-android/issues/445)? It's currently 'Done', should we use the same checkmark button as in the text editing view? Or perhaps a back arrow?

**Comment by megsfulton** [comment]
Let's use the checkmark there.

**Comment by aforcier** [comment]
Addressed in #563.
