### ISSUE TITLE
Intro to stories screen design updates

### ISSUE THREAD

**Issue by megsfulton** [Automattic/portkey-android#575]
Feedback:
- Remove story titles below the images 
- Left align the story images with the text instead of centering. This will keep things from getting wonky when the device is rotated. 

Questions:
1. Are those the default android text styles inherited from the what's new screen? The line height is looking tight

**Comment by aforcier** [comment]
> Left align the story images with the text instead of centering. This will keep things from getting wonky when the device is rotated.

Interesting, it looked okay on my device, if a bit spacious (maybe that's what you mean):

![intro-stories-landscape](https://user-images.githubusercontent.com/9613966/96521190-a90f6c80-12ab-11eb-8a5e-5af02c4b66cc.png)

Do you mean they should be left aligned each within their half of the screen, or totally left aligned? If the latter, how much padding are you thinking?

> 1. Are those the default android text styles inherited from the what's new screen? The line height is looking tight

They are. I can add some extra line height to our implementation though. Here's what a line height multiplier of 1.2 would look like (applied to both grey text blocks):

<img width="238" alt="Screen Shot 2020-10-20 at 8 21 37 AM" src="https://user-images.githubusercontent.com/9613966/96521966-6a7ab180-12ad-11eb-8248-ff6ed9efdb9a.png">

**Comment by megsfulton** [comment]
> Do you mean they should be left aligned each within their half of the screen, or totally left aligned? If the latter, how much padding are you thinking?

Totally left aligned so that the first story is left aligned with the text and the second story retains the amount of padding / margin that it currently has on the left between stories. 

> They are. I can add some extra line height to our implementation though. Here's what a line height multiplier of 1.2 would look like (applied to both grey text blocks):

That feels a lot better. Can you add a little extra space between the headlines "Now stories are..." and "Story posts don't..." and the text block below them?

**Comment by aforcier** [comment]
<img width="238" alt="Screen Shot 2020-10-21 at 10 16 17 AM" src="https://user-images.githubusercontent.com/9613966/96661313-bcdbd100-1386-11eb-9e2e-e36fe80a7714.png">
<img width="369" alt="Screen Shot 2020-10-21 at 10 16 29 AM" src="https://user-images.githubusercontent.com/9613966/96661315-be0cfe00-1386-11eb-91c9-ccaaf155fd9b.png">

How does that look @megsfulton ?

* Left aligned images
* Roughly same padding as before
* Extra space under headlines
* Line spacing kept from before

**Comment by megsfulton** [comment]
Looks good 🚢
