### ISSUE TITLE
Trash icon discoverability: discussion

### ISSUE THREAD

**Issue by mzorz** [Automattic/portkey-android#583]
> It took me a while to figure out I have to tap an image twice to see the delete icon

Another report:

> Long press to delete text is not super intuitive to me (but I primarily use iOS, long press gesture might be more common in Android. In Instagram iOS, the trash icon appears when dragging the text around and it’s clear that I can delete text.

cc @aforcier and @megsfulton for discussion - marking as enhancement for now

**Comment by megsfulton** [comment]
Was discussing this in slack with @aforcier who suggested we try this:

> We could look into adding a second way to delete a slide: long-pressing any slide will switch to that slide and show the delete view at the same time.

**Comment by mzorz** [comment]
Just adding another report:
>  Ohhh! You have to tap the slide twice to make the trash can appear! Yeah, that wasn’t what I expected. 🙂

Ref: pbMoDN-1lv#comment-2777
