### ISSUE TITLE
Text edit controls: bottom sheet clipped

### ISSUE THREAD

**Issue by mzorz** [Automattic/portkey-android#597]
> On my device (Samsung Galaxy S10 Lite) the bottom row of “Background” colors was clipped:

![image](https://user-images.githubusercontent.com/6597771/97287850-d2884500-1823-11eb-95d5-0cb4fa68e402.png)

Ref: pbMoDN-1lv#comment-2775

**Comment by mzorz** [comment]
Just an observation, I think the same bottom sheet height issue observed in publish bottom sheet in #598 is somewhat related (not same code but same root problem)

**Comment by aforcier** [comment]
One more similar report: (pbMoDN-1lv-p2#comment-3137)

> Maybe intentional or related to my specific device with Oxygen OS and gestures replacing standard navigation bar. In my case the background colors row is not cut, but have no spacing below and it touches the bottom border

![backrow](https://user-images.githubusercontent.com/9613966/99606942-11d63a00-2a4e-11eb-89ff-97c53249c305.png)
