### ISSUE TITLE
Adding media to a story from the block editor opens up the camera capture view without a way to access WP or device media

### ISSUE THREAD

**Issue by megsfulton** [Automattic/portkey-android#617]
Steps:

1) Add story block to post
2) Tap empty block to add media 
3) Camera capture opens without the thumbnail to access the device photos - the only option to proceed forward is to take a photo 

Is there a way to change this so that the flow is the same as creating a story from the create sheet where we show the media picker?

**Comment by aforcier** [comment]
I think this came up before - @mzorz mentioned it's something we can change but is surprisingly tricky to do. We had decided to leave it for v1 but it's good to capture it.

Swiping up from the bottom still works to show the photo picker, but that's not very discoverable.

**Comment by mzorz** [comment]
> Is there a way to change this so that the flow is the same as creating a story from the create sheet where we show the media picker?

Yes this is tracked here: https://github.com/Automattic/stories-android/issues/593
It involved refactoring and reusing code to receive the data from the picker.

> Camera capture opens without the thumbnail to access the device photos 

The thumbnail was removed long time ago but I _think_ we can get it back for this specific case as a quick workaround for v1, wdyt @megsfulton @aforcier ?

**Comment by megsfulton** [comment]
> The thumbnail was removed long time ago but I think we can get it back for this specific case as a quick workaround for v1

That sgtm

**Comment by aforcier** [comment]
Sounds like a plan 👍
