### ISSUE TITLE
Story icon in the block inserter doesn't match the other icons

### ISSUE THREAD

**Issue by megsfulton** [Automattic/portkey-android#618]
The story icon looks different from the other icons in the block inserter list. 

It's a different size and color. Can we update it to match the others? 

Happy to provide an updated asset if ones needed.

**Comment by mzorz** [comment]
Fixed in https://github.com/Automattic/jetpack/pull/17962

**Comment by aforcier** [comment]
Fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/13534.
