### ISSUE TITLE
Implement View binding, replacing synthetics

### ISSUE THREAD

**Issue by mzorz** [Automattic/portkey-android#628]
The Stories library uses synthetics and it's being deprecated in favor of View bindings.

See https://android-developers.googleblog.com/2020/11/the-future-of-kotlin-android-extensions.html
and https://developer.android.com/topic/libraries/view-binding/migration

**Comment by faranjit** [comment]
Hi, 
Is there anyone doing this or i can do it?

**Comment by aforcier** [comment]
@faranjit no one's working on this, you're welcome to tackle it! However I can't promise a quick merge of the change, since we'd likely want to coordinate with the WordPress-Android repository changing over as well, which hasn't started yet.
